print("Hello, Word!")
print('Hello, Word!')
print()
print('Hello\nWord!')
print('Hello\\nWord!')
print('Hello\\\nWord!')
print()
#print() with more than one arg and keyword arguments
print('My name is', 'Bond', end=' ')
print('James Bond.')
print()
print('My', 'name', 'is', 'James', 'Bond', sep='-')
print('Programming', 'Essentials', sep='***', end='***')
print('in', 'Python', sep='...')
#print an arrow
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)